name: Move issue

on:
  issues:
    types:
      - assigned

jobs:
  move_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@7ffb872c64bd809d23563a130a0a97d01dfa8f43
        with:
          project: dan-sic's test project
          column: In Progress
          repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}