name: Remove Issue Label

on:
  project_card:
    types:
      - moved
  
jobs:
  remove_label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Debug
        run: echo "${{ github.event.project_card }}"
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(JSON.stringify(context))